[build]
target = "x86_64-pc-windows-gnullvm"

[target.x86_64-pc-windows-gnullvm]
linker = "work/toolchains/llvm-mingw-20260826-ucrt-x86_64/bin/x86_64-w64-mingw32-clang.exe"
ar = "work/toolchains/llvm-mingw-20260826-ucrt-x86_64/bin/llvm-ar.exe"
