<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { CheckCircle2, Clock3, Image, LogOut, ShieldAlert, Trash2, Upload, UserRound } from 'lucide-vue-next'
import BrandMark from '../components/BrandMark.vue'
import { api } from '../api'; import { auth } from '../auth'; import { tr } from '../preferences'
const router=useRouter(),status=computed(()=>auth.state.user?.approval_status||'pending')
const title=computed(()=>status.value==='approved'?tr('Учётная запись одобрена','Account approved'):status.value==='rejected'?tr('Заявка отклонена','Registration rejected'):tr('Ожидает подтверждения','Awaiting approval'))
const avatarFile=ref<File|null>(null),avatarBusy=ref(false),avatarVersion=ref(Date.now()),avatarNotice=ref(''),avatarError=ref('')
async function logout(){await auth.logout();await router.replace('/account/login')}
function selectAvatar(event:Event){avatarFile.value=(event.target as HTMLInputElement).files?.[0]||null}
async function uploadAvatar(){if(!avatarFile.value)return;avatarBusy.value=true;avatarError.value='';try{const result=await api.uploadMyAvatar(avatarFile.value);avatarFile.value=null;avatarVersion.value=Date.now();if(auth.state.user)auth.state.user.avatar=result.avatar;avatarNotice.value=tr('Аватар обновлён. Перезайдите в RustDesk Client, чтобы он применился.','Avatar updated. Sign in to RustDesk Client again to apply it.')}catch(reason){avatarError.value=reason instanceof Error?reason.message:tr('Не удалось загрузить аватар','Could not upload avatar')}finally{avatarBusy.value=false}}
async function resetAvatar(){avatarBusy.value=true;avatarError.value='';try{await api.resetMyAvatar();avatarVersion.value=Date.now();avatarNotice.value=tr('Теперь используется глобальный аватар.','The global avatar is now used.')}catch(reason){avatarError.value=reason instanceof Error?reason.message:tr('Не удалось удалить аватар','Could not remove avatar')}finally{avatarBusy.value=false}}
</script>
<template><main class="account-page"><header class="account-portal-header"><div class="login-brand"><BrandMark/><div><strong>Remote Control Server</strong><span>{{tr('Личный кабинет','User portal')}}</span></div></div><button class="secondary-button" @click="logout"><LogOut :size="16"/>{{tr('Выйти','Sign out')}}</button></header><div class="account-portal-layout"><section class="account-portal-card panel"><span class="account-status-icon" :class="status"><CheckCircle2 v-if="status==='approved'"/><ShieldAlert v-else-if="status==='rejected'"/><Clock3 v-else/></span><p class="overline">{{tr('Статус доступа','Access status')}}</p><h1>{{title}}</h1><p v-if="status==='pending'">{{tr('Администратор ещё не рассмотрел регистрацию. Новые подключения блокируются непосредственно на HBBS.','Your registration has not been reviewed yet. HBBS blocks new remote connections.')}}</p><p v-else-if="status==='approved'">{{tr('Вы можете войти в официальный RustDesk Client с теми же данными. Доступ дополнительно определяется ACL.','You can sign in to the official RustDesk Client with the same credentials. Access is also controlled by ACL.')}}</p><p v-else>{{tr('Обратитесь к администратору организации.','Contact your organization administrator.')}}</p><dl class="settings-list"><div><dt>{{tr('Пользователь','User')}}</dt><dd><UserRound :size="15"/>{{auth.state.user?.username}}</dd></div><div><dt>Email</dt><dd>{{auth.state.user?.email||'—'}}</dd></div><div><dt>{{tr('Роль','Role')}}</dt><dd>{{auth.state.user?.role}}</dd></div></dl></section><section class="account-portal-card panel account-avatar-card"><img :src="`${auth.state.user?.avatar}?v=${avatarVersion}`" alt=""/><div><p class="overline">Connection identity</p><h2>{{tr('Ваш аватар','Your avatar')}}</h2><p>{{tr('Показывается удалённому пользователю при входящем подключении. Персональный аватар имеет приоритет над глобальным.','Shown to the remote user for incoming connections. Your personal avatar overrides the global avatar.')}}</p></div><p v-if="avatarError" class="alert-error">{{avatarError}}</p><p v-if="avatarNotice" class="alert-success">{{avatarNotice}}</p><label class="logo-file"><Image :size="17"/><input type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg" :disabled="avatarBusy" @change="selectAvatar"/><span>{{avatarFile?.name||tr('Выбрать PNG или JPEG','Choose PNG or JPEG')}}</span></label><div class="logo-actions"><button class="secondary-button" :disabled="avatarBusy||!avatarFile" @click="uploadAvatar"><Upload :size="16"/>{{tr('Загрузить','Upload')}}</button><button class="secondary-button" :disabled="avatarBusy" @click="resetAvatar"><Trash2 :size="16"/>{{tr('Использовать глобальный','Use global')}}</button></div></section></div></main></template>
