<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Ban, ChevronLeft, ChevronRight, Download, LogIn, RefreshCw, Search, ShieldCheck, X } from 'lucide-vue-next'
import { api } from '../api'
import { t, tr } from '../preferences'
import type { AuditEvent, AuditQuery, AuditSummary } from '../types'

const records=ref<AuditEvent[]>([]),summary=ref<AuditSummary>(),facets=ref<AuditSummary>(),selected=ref<AuditEvent>(),loading=ref(true),error=ref('')
const limit=50,offset=ref(0),total=ref(0)
const filters=reactive({search:'',type:'',result:'',actor_user_id:'',target_id:'',ip:'',from:'',to:''})
const pageNumber=computed(()=>Math.floor(offset.value/limit)+1)
const pageCount=computed(()=>Math.max(1,Math.ceil(total.value/limit)))
const metadata=computed(()=>selected.value?.metadata?JSON.stringify(selected.value.metadata,null,2):'{}')
const eventTypes=computed(()=>Object.keys(facets.value?.by_type||{}).sort())
function query(includePage=true):AuditQuery{return {limit:includePage?limit:undefined,offset:includePage?offset.value:undefined,search:filters.search||undefined,type:filters.type||undefined,result:filters.result||undefined,actor_user_id:filters.actor_user_id||undefined,target_id:filters.target_id||undefined,ip:filters.ip||undefined,from:filters.from?new Date(filters.from).toISOString():undefined,to:filters.to?new Date(filters.to).toISOString():undefined}}
async function load(reset=false){if(reset)offset.value=0;loading.value=true;error.value='';try{const [page,stats,allStats]=await Promise.all([api.queryAudit(query()),api.auditSummary(query(false)),api.auditSummary({})]);records.value=page.events;total.value=page.total;summary.value=stats;facets.value=allStats}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить аудит','Unable to load audit')}finally{loading.value=false}}
function localInput(date:Date){const shifted=new Date(date.getTime()-date.getTimezoneOffset()*60000);return shifted.toISOString().slice(0,16)}
function setPeriod(hours:number){const end=new Date(),start=new Date(end.getTime()-hours*3600000);filters.from=localInput(start);filters.to=localInput(end);void load(true)}
async function exportCSV(){try{const result=await api.exportAudit(query(false));const url=URL.createObjectURL(result.blob);const link=document.createElement('a');link.href=url;link.download=result.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось экспортировать аудит','Unable to export audit')}}
function changePage(direction:number){offset.value=Math.max(0,Math.min((pageCount.value-1)*limit,offset.value+direction*limit));void load()}
function showConnections(){filters.type='connection_allowed';filters.result='allowed';void load(true)}
function showFileTransfers(){filters.type='file_transfer';filters.result='success';void load(true)}
function metaText(event:AuditEvent,key:string){const value=event.metadata?.[key];return typeof value==='string'?value:''}
function controllerName(event:AuditEvent){return metaText(event,'controller_display_name')||metaText(event,'controller_login')||event.controller_device_id||event.actor_user_id?.slice(0,8)||'system'}
function targetName(event:AuditEvent){const name=metaText(event,'target_alias')||metaText(event,'target_hostname');return name?`${name} · ${event.target_rustdesk_id}`:event.target_rustdesk_id||'—'}
function eventName(value:string){const names:Record<string,[string,string]>={connection_started:['Подключение начато','Connection started'],connection_updated:['Подключение обновлено','Connection updated'],connection_closed:['Подключение завершено','Connection closed'],file_transfer:['Передача файла','File transfer'],connection_allowed:['Подключение разрешено','Connection allowed'],connection_denied:['Подключение запрещено','Connection denied'],login_success:['Успешный вход','Successful sign-in'],login_failed:['Неудачный вход','Failed sign-in'],device_import:['Импорт устройств','Device import'],device_archive:['Устройство архивировано','Device archived'],device_restore:['Устройство восстановлено','Device restored']};const copy=names[value];return copy?tr(copy[0],copy[1]):value}
function eventSubject(event:AuditEvent){if(event.type==='file_transfer'){const name=metaText(event,'file_name')||metaText(event,'path');return name?`${eventName(event.type)} · ${name}`:eventName(event.type)}return eventName(event.type)}
onMounted(()=>load())
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Security history</p><h2>{{t('auditTrail')}}</h2><p>{{tr('Серверный поиск, аналитика подключений и полный журнал изменений.','Server-side search, connection analytics, and complete change history.')}}</p></div><div class="heading-actions"><button class="secondary-button" @click="exportCSV"><Download :size="16"/>CSV</button><button class="secondary-button" :disabled="loading" @click="load()"><RefreshCw :size="16" :class="{spinning:loading}"/>{{t('refresh')}}</button></div></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <section class="audit-summary"><div><ShieldCheck :size="18"/><span><strong>{{summary?.total??0}}</strong>{{tr('Событий','Events')}}</span></div><div class="online"><ShieldCheck :size="18"/><span><strong>{{summary?.allowed_connections??0}}</strong>{{tr('Разрешено','Allowed')}}</span></div><div class="offline"><Ban :size="18"/><span><strong>{{summary?.denied_connections??0}}</strong>{{tr('Отклонено','Denied')}}</span></div><div><LogIn :size="18"/><span><strong>{{summary?.failed_logins??0}}</strong>{{tr('Ошибок входа','Failed logins')}}</span></div></section>
  <section class="panel table-panel"><div class="audit-presets"><span>{{tr('Период','Period')}}:</span><button @click="setPeriod(24)">24h</button><button @click="setPeriod(168)">7d</button><button @click="setPeriod(720)">30d</button><button @click="showConnections">{{tr('История подключений','Connection history')}}</button><button @click="showFileTransfers">{{tr('Передача файлов','File transfers')}}</button></div><form class="audit-filters" @submit.prevent="load(true)"><div class="search-box"><Search :size="17"/><input v-model.trim="filters.search" :placeholder="tr('Логин, псевдоним, ID, IP или причина','Login, alias, ID, IP, or reason')"/></div><select v-model="filters.type"><option value="">{{tr('Все события','All events')}}</option><option v-for="value in eventTypes" :key="value" :value="value">{{value}} ({{facets?.by_type[value]}})</option></select><select v-model="filters.result"><option value="">{{tr('Все результаты','All results')}}</option><option value="allowed">allowed</option><option value="success">success</option><option value="denied">denied</option><option value="failed">failed</option></select><input v-model.trim="filters.actor_user_id" :placeholder="tr('UUID пользователя','User UUID')"/><input v-model.trim="filters.target_id" :placeholder="tr('ID устройства','Device ID')"/><input v-model.trim="filters.ip" placeholder="IP"/><input v-model="filters.from" type="datetime-local" :title="tr('Начало периода','Period start')"/><input v-model="filters.to" type="datetime-local" :title="tr('Конец периода','Period end')"/><button class="primary-button compact">{{tr('Применить','Apply')}}</button></form>
    <div class="table-scroll"><table><thead><tr><th>{{t('time')}}</th><th>{{t('event')}}</th><th>{{tr('Пользователь','User')}}</th><th>{{tr('Целевое устройство','Target device')}}</th><th>{{t('ipAddress')}}</th><th>{{t('result')}}</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="empty-cell">{{t('loading')}}</td></tr><tr v-else-if="!records.length"><td colspan="6" class="empty-cell">{{t('noRecords')}}</td></tr><tr v-for="event in records" :key="event.id" class="clickable-row" @click="selected=event"><td>{{new Date(event.occurred_at).toLocaleString()}}</td><td><strong>{{eventSubject(event)}}</strong><small v-if="event.reason" class="row-detail">{{event.reason}}</small><small v-else-if="event.type==='file_transfer'&&metaText(event,'path')!==metaText(event,'file_name')" class="row-detail">{{metaText(event,'path')}}</small></td><td><strong>{{controllerName(event)}}</strong><small v-if="event.controller_device_id&&controllerName(event)!==event.controller_device_id" class="row-detail mono-cell">{{event.controller_device_id}}</small></td><td class="mono-cell">{{targetName(event)}}</td><td>{{event.ip||'—'}}</td><td><span class="badge" :class="event.result==='denied'||event.result==='failed'?'danger':'green'">{{event.result||tr('записано','recorded')}}</span></td></tr></tbody></table></div>
    <footer class="table-pagination"><span>{{total?offset+1:0}}–{{Math.min(offset+limit,total)}} {{tr('из','of')}} {{total}}</span><div><button class="icon-btn" :disabled="offset===0" @click="changePage(-1)"><ChevronLeft :size="17"/></button><strong>{{pageNumber}} / {{pageCount}}</strong><button class="icon-btn" :disabled="pageNumber>=pageCount" @click="changePage(1)"><ChevronRight :size="17"/></button></div></footer>
  </section>
  <div v-if="selected" class="modal-backdrop" @click.self="selected=undefined"><article class="modal-card audit-detail"><div class="modal-heading"><div><p class="overline">{{selected.id}}</p><h3>{{eventName(selected.type)}}</h3></div><button class="icon-btn" @click="selected=undefined"><X :size="20"/></button></div><dl class="settings-list"><div><dt>{{t('time')}}</dt><dd>{{new Date(selected.occurred_at).toLocaleString()}}</dd></div><div><dt>{{tr('Пользователь / сессия','User / session')}}</dt><dd class="mono-cell">{{selected.actor_user_id||'—'}} / {{selected.actor_session_id||'—'}}</dd></div><div><dt>{{tr('Контроллер / цель','Controller / target')}}</dt><dd class="mono-cell">{{selected.controller_device_id||'—'}} / {{selected.target_rustdesk_id||'—'}}</dd></div><div><dt>IP / result</dt><dd>{{selected.ip||'—'}} / {{selected.result||'—'}}</dd></div><div><dt>{{tr('Причина','Reason')}}</dt><dd>{{selected.reason||'—'}}</dd></div></dl><label><span>Metadata</span><pre>{{metadata}}</pre></label></article></div>
</template>

<style scoped>
.audit-presets{display:flex;align-items:center;gap:6px;padding:10px 14px 0;color:var(--muted);font-size:9px}.audit-presets button{padding:4px 8px;border:1px solid var(--border);border-radius:12px;background:var(--surface-2);color:var(--muted);font-size:9px}.audit-presets button:hover{color:var(--text);border-color:var(--accent)}
.audit-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.audit-summary>div{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.audit-summary svg{color:var(--accent)}.audit-summary .offline svg{color:var(--danger)}.audit-summary span,.audit-summary strong{display:block}.audit-summary span{color:var(--muted);font-size:10px}.audit-summary strong{margin-bottom:3px;color:var(--text);font-size:20px}.audit-filters{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(5,minmax(120px,1fr)) auto;gap:8px;padding:14px;border-bottom:1px solid var(--border)}.audit-filters .search-box{width:auto}.audit-filters>input,.audit-filters>select{min-width:0;height:36px;padding:0 9px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--text);font-size:10px}.clickable-row{cursor:pointer}.table-pagination{display:flex;align-items:center;justify-content:space-between;padding:11px 16px;border-top:1px solid var(--border);color:var(--muted);font-size:10px}.table-pagination>div{display:flex;align-items:center;gap:10px}.audit-detail{width:min(720px,100%)}.audit-detail dd{max-width:70%;overflow-wrap:anywhere;text-align:right}.audit-detail pre{max-height:250px;margin:0;padding:12px;overflow:auto;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--text);font-size:10px;white-space:pre-wrap}@media(max-width:1200px){.audit-filters{grid-template-columns:repeat(3,1fr)}.audit-filters .search-box{grid-column:span 2}}@media(max-width:700px){.audit-summary{grid-template-columns:repeat(2,1fr)}.audit-filters{grid-template-columns:1fr}.audit-filters .search-box{grid-column:auto}}
</style>
