<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Bot, Pencil, Plus, Trash2, X } from 'lucide-vue-next'
import { api } from '../api'
import { auth } from '../auth'
import { tr } from '../preferences'
import type { AutomationRule, AutomationRun } from '../types'

const rules=ref<AutomationRule[]>([]),runs=ref<AutomationRun[]>([]),loading=ref(true),saving=ref(false),open=ref(false),error=ref(''),editing=ref<AutomationRule>()
const form=reactive({name:'',event_type:'AUDIT_RECORDED',audit_type:'login_failed',result:'',severity:'warning' as AutomationRule['severity'],throttle_seconds:300,notify:true,webhook:false,enabled:true})
async function load(){loading.value=true;error.value='';try{[rules.value,runs.value]=await Promise.all([api.automationRules(),api.automationRuns()])}catch(reason){error.value=reason instanceof Error?reason.message:tr('Автоматизация недоступна','Automation unavailable')}finally{loading.value=false}}
function add(){editing.value=undefined;Object.assign(form,{name:'',event_type:'AUDIT_RECORDED',audit_type:'login_failed',result:'',severity:'warning',throttle_seconds:300,notify:true,webhook:false,enabled:true});open.value=true}
function edit(value:AutomationRule){editing.value=value;Object.assign(form,{name:value.name,event_type:value.event_types[0]||'AUDIT_RECORDED',audit_type:value.conditions.type||'',result:value.conditions.result||'',severity:value.severity,throttle_seconds:value.throttle_seconds,notify:value.actions.includes('notification'),webhook:value.actions.includes('webhook'),enabled:value.enabled});open.value=true}
function payload(){const conditions:Record<string,string>={};if(form.audit_type)conditions.type=form.audit_type;if(form.result)conditions.result=form.result;const actions:string[]=[];if(form.notify)actions.push('notification');if(form.webhook)actions.push('webhook');return{name:form.name,event_types:[form.event_type],conditions,actions,severity:form.severity,throttle_seconds:form.throttle_seconds,enabled:form.enabled}}
async function save(){if(!form.notify&&!form.webhook){error.value=tr('Выберите хотя бы одно действие','Select at least one action');return}saving.value=true;error.value='';try{editing.value?await api.updateAutomationRule(editing.value.id,payload()):await api.createAutomationRule(payload());open.value=false;await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось сохранить правило','Unable to save rule')}finally{saving.value=false}}
async function toggle(value:AutomationRule){await api.updateAutomationRule(value.id,{...value,enabled:!value.enabled});await load()}
async function remove(value:AutomationRule){if(confirm(tr(`Удалить правило «${value.name}»?`,`Delete rule “${value.name}”?`))){await api.deleteAutomationRule(value.id);await load()}}
onMounted(load)
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Event-driven operations</p><h2>{{tr('Автоматизация','Automation')}}</h2><p>{{tr('Правила реагируют на внутренние события, создают уведомления и запускают подписанные Webhooks.','Rules react to internal events, create notifications, and invoke signed webhooks.')}}</p></div><button v-if="auth.can('automation.write')" class="primary-button compact" @click="add"><Plus :size="17"/>{{tr('Добавить правило','Add rule')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p><p v-if="loading" class="panel empty-state">{{tr('Загрузка…','Loading…')}}</p>
  <section v-else class="automation-layout">
    <article class="panel table-panel"><div class="panel-heading padded"><div><p class="overline">Rules</p><h3>{{tr('Активные сценарии','Active workflows')}}</h3></div><Bot :size="20"/></div><div class="table-scroll"><table><thead><tr><th>{{tr('Правило','Rule')}}</th><th>{{tr('Событие','Event')}}</th><th>{{tr('Действия','Actions')}}</th><th>Throttle</th><th></th></tr></thead><tbody><tr v-if="!rules.length"><td colspan="5" class="empty-cell">{{tr('Правил пока нет.','No rules yet.')}}</td></tr><tr v-for="rule in rules" :key="rule.id"><td><strong>{{rule.name}}</strong><small class="row-subtle"><span class="badge" :class="rule.enabled?'green':'neutral'">{{rule.enabled?'ON':'OFF'}}</span> · {{rule.severity}}</small></td><td><span class="mono-cell">{{rule.event_types.join(', ')}}</span><small class="row-subtle mono-cell">{{Object.entries(rule.conditions).map(([key,value])=>`${key}=${value}`).join(', ')||'—'}}</small></td><td>{{rule.actions.join(', ')}}</td><td>{{rule.throttle_seconds}}s</td><td class="actions-cell"><button class="icon-btn" @click="edit(rule)"><Pencil :size="16"/></button><button class="text-button" @click="toggle(rule)">{{rule.enabled?'OFF':'ON'}}</button><button class="icon-btn danger-text" @click="remove(rule)"><Trash2 :size="16"/></button></td></tr></tbody></table></div></article>
    <article class="panel table-panel"><div class="panel-heading padded"><div><p class="overline">Execution history</p><h3>{{tr('Последние срабатывания','Recent runs')}}</h3></div></div><div class="table-scroll"><table><thead><tr><th>{{tr('Время','Time')}}</th><th>{{tr('Правило','Rule')}}</th><th>{{tr('Событие','Event')}}</th><th>{{tr('Статус','Status')}}</th></tr></thead><tbody><tr v-if="!runs.length"><td colspan="4" class="empty-cell">{{tr('Срабатываний пока нет.','No runs yet.')}}</td></tr><tr v-for="run in runs" :key="run.id"><td>{{new Date(run.created_at).toLocaleString()}}</td><td>{{rules.find(rule=>rule.id===run.rule_id)?.name||run.rule_id}}</td><td class="mono-cell">{{run.event_type}}</td><td><span class="badge" :class="run.status==='completed'?'green':'red'">{{run.status}}</span></td></tr></tbody></table></div></article>
  </section>
  <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal-card" @submit.prevent="save"><div class="modal-heading"><h3>{{editing?tr('Изменить правило','Edit rule'):tr('Новое правило','New rule')}}</h3><button type="button" class="icon-btn" @click="open=false"><X :size="20"/></button></div><label><span>{{tr('Название','Name')}}</span><input v-model.trim="form.name" minlength="2" maxlength="128" required/></label><div class="form-grid"><label><span>{{tr('Событие','Event')}}</span><select v-model="form.event_type"><option>AUDIT_RECORDED</option><option>USER_UPDATED</option><option>USER_DISABLED</option><option>SESSION_CREATED</option><option>SESSION_REVOKED</option><option>DEVICE_UPDATED</option><option>RELAY_UPDATED</option></select></label><label><span>{{tr('Тип audit-события','Audit event type')}}</span><input v-model.trim="form.audit_type" placeholder="login_failed"/></label><label><span>{{tr('Результат','Result')}}</span><input v-model.trim="form.result" placeholder="denied"/></label><label><span>{{tr('Важность','Severity')}}</span><select v-model="form.severity"><option>info</option><option>warning</option><option>critical</option></select></label><label><span>Throttle, sec</span><input v-model.number="form.throttle_seconds" type="number" min="0" max="2592000"/></label><label v-if="editing" class="check-label"><input v-model="form.enabled" type="checkbox"/><span>{{tr('Правило включено','Rule enabled')}}</span></label></div><fieldset class="action-fieldset"><legend>{{tr('Действия','Actions')}}</legend><label class="check-label"><input v-model="form.notify" type="checkbox"/><span>{{tr('Уведомление администратора','Administrator notification')}}</span></label><label class="check-label"><input v-model="form.webhook" type="checkbox"/><span>{{tr('Подписанный Webhook','Signed webhook')}}</span></label></fieldset><div class="modal-actions"><button type="button" class="secondary-button" @click="open=false">{{tr('Отмена','Cancel')}}</button><button class="primary-button compact" :disabled="saving">{{saving?tr('Сохранение…','Saving…'):tr('Сохранить','Save')}}</button></div></form></div>
</template>

<style scoped>
.action-fieldset{display:flex;gap:20px;margin:15px 0;padding:13px;border:1px solid var(--border);border-radius:10px}.action-fieldset legend{padding:0 7px;color:var(--muted);font-size:10px}.row-subtle{display:block;margin-top:4px}
</style>
