<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArchiveRestore, DatabaseBackup, Download, HardDrive, Plus, RefreshCw, ShieldCheck, Trash2, Upload, Users } from 'lucide-vue-next'
import { api } from '../api'
import { auth } from '../auth'
import { tr } from '../preferences'
import type { BackupArtifact, BackupInspection } from '../types'

const records=ref<BackupArtifact[]>([]),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),restoreFile=ref<File>(),pending=ref(false),retention=ref(0),intervalSeconds=ref(0),inspection=ref<BackupInspection>()
const totalBytes=computed(()=>records.value.reduce((sum,value)=>sum+value.size_bytes,0))
function size(value:number){if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KiB`;return `${(value/1048576).toFixed(1)} MiB`}
async function load(){loading.value=true;error.value='';try{const [values,status]=await Promise.all([api.managedBackups(),api.restoreStatus()]);records.value=values;pending.value=status.pending;retention.value=status.retention;intervalSeconds.value=status.interval_seconds}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить резервные копии','Unable to load backups')}finally{loading.value=false}}
async function create(){busy.value=true;error.value='';notice.value='';try{const value=await api.createManagedBackup();await load();notice.value=tr(`Создана резервная копия ${value.name}.`,`Backup ${value.name} created.`)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось создать резервную копию','Unable to create backup')}finally{busy.value=false}}
async function download(value:BackupArtifact){try{const result=await api.downloadManagedBackup(value.name);const url=URL.createObjectURL(result.blob);const link=document.createElement('a');link.href=url;link.download=result.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось скачать резервную копию','Unable to download backup')}}
async function remove(value:BackupArtifact){if(!confirm(tr(`Удалить ${value.name}?`,`Delete ${value.name}?`)))return;busy.value=true;try{await api.deleteManagedBackup(value.name);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить резервную копию','Unable to delete backup')}finally{busy.value=false}}
function selectRestore(event:Event){restoreFile.value=(event.target as HTMLInputElement).files?.[0];inspection.value=undefined;error.value=''}
async function stage(){if(!restoreFile.value||!confirm(tr('Проверить и подготовить эту базу к восстановлению при следующем перезапуске контейнера?','Validate and stage this database for restoration on the next container restart?')))return;busy.value=true;error.value='';notice.value='';try{const result=await api.stageRestore(restoreFile.value);inspection.value=result.inspection;pending.value=true;restoreFile.value=undefined;notice.value=tr('Копия проверена и подготовлена. Перезапустите контейнер один раз для применения.','Backup validated and staged. Restart the container once to apply it.')}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось подготовить восстановление','Unable to stage restore')}finally{busy.value=false}}
async function cancelRestore(){if(!confirm(tr('Отменить подготовленное восстановление?','Cancel the staged restore?')))return;busy.value=true;try{await api.cancelRestore();pending.value=false;inspection.value=undefined;notice.value=tr('Подготовленное восстановление отменено.','Staged restore cancelled.')}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось отменить восстановление','Unable to cancel restore')}finally{busy.value=false}}
onMounted(load)
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Disaster recovery</p><h2>{{tr('Резервные копии','Backups')}}</h2><p>{{tr('Автоматические согласованные SQLite-снапшоты, retention и безопасное восстановление после проверки.','Automatic consistent SQLite snapshots, retention, and validated disaster recovery.')}}</p></div><div class="heading-actions"><button class="secondary-button" :disabled="loading" @click="load"><RefreshCw :size="16" :class="{spinning:loading}"/>{{tr('Обновить','Refresh')}}</button><button class="primary-button compact" :disabled="busy||!auth.can('backup.write')" @click="create"><Plus :size="16"/>{{tr('Создать backup','Create backup')}}</button></div></section>
  <p v-if="error" class="alert-error">{{error}}</p><p v-if="notice" class="alert-success">{{notice}}</p>
  <section class="backup-summary"><div><DatabaseBackup/><span><strong>{{records.length}} / {{retention||'—'}}</strong>{{tr('Снапшотов / retention','Snapshots / retention')}}</span></div><div><HardDrive/><span><strong>{{size(totalBytes)}}</strong>{{tr('Занято','Stored')}}</span></div><div><Users/><span><strong>{{records[0]?.users??0}}</strong>{{tr('Пользователей в последнем','Users in latest')}}</span></div><div><ShieldCheck/><span><strong>{{intervalSeconds?`${Math.round(intervalSeconds/3600)}h`:'—'}}</strong>{{tr('Интервал','Interval')}}</span></div></section>
  <section v-if="pending" class="restore-warning"><ArchiveRestore :size="22"/><div><strong>{{tr('Восстановление подготовлено','Restore staged')}}</strong><p>{{tr('При следующем перезапуске контейнера текущая база и WAL-файлы будут сохранены в каталоге pre-restore, после чего проверенная копия будет установлена атомарно.','On the next container restart, the current database and WAL files are preserved in a pre-restore directory before the validated copy is installed atomically.')}}</p></div><button class="secondary-button" :disabled="busy||!auth.can('backup.write')" @click="cancelRestore">{{tr('Отменить','Cancel')}}</button></section>
  <section class="backup-layout"><article class="panel table-panel"><div class="panel-heading padded"><div><p class="overline">Retention storage</p><h3>{{tr('Сохранённые копии','Stored snapshots')}}</h3></div></div><div class="table-scroll"><table><thead><tr><th>{{tr('Создана','Created')}}</th><th>{{tr('Размер','Size')}}</th><th>{{tr('Пользователи','Users')}}</th><th>{{tr('Устройства','Devices')}}</th><th>{{tr('Сессии','Sessions')}}</th><th></th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="empty-cell">{{tr('Загрузка…','Loading…')}}</td></tr><tr v-else-if="!records.length"><td colspan="6" class="empty-cell">{{tr('Резервных копий пока нет.','No backups yet.')}}</td></tr><tr v-for="value in records" :key="value.name"><td><strong>{{new Date(value.created_at).toLocaleString()}}</strong><small class="row-subtle mono-cell">{{value.name}}</small></td><td>{{size(value.size_bytes)}}</td><td>{{value.users}}</td><td>{{value.devices}}</td><td>{{value.sessions}}</td><td class="actions-cell"><button class="icon-btn" :title="tr('Скачать','Download')" @click="download(value)"><Download :size="16"/></button><button v-if="auth.can('backup.write')" class="icon-btn danger-text" :title="tr('Удалить','Delete')" :disabled="busy" @click="remove(value)"><Trash2 :size="16"/></button></td></tr></tbody></table></div></article>
    <article class="panel restore-card"><div class="panel-heading"><div><p class="overline">Validated restore</p><h3>{{tr('Восстановление','Restore')}}</h3></div><ArchiveRestore :size="20"/></div><p>{{tr('Загрузите SQLite backup. Сервер проверит quick_check и обязательную схему, но не изменит рабочую базу до следующего запуска контейнера.','Upload a SQLite backup. The server validates quick_check and the required schema, but does not alter the active database until the next container start.')}}</p><label class="restore-file"><Upload :size="18"/><input type="file" accept=".db,.sqlite,.sqlite3,application/vnd.sqlite3" :disabled="busy||pending||!auth.can('backup.write')" @change="selectRestore"/><span>{{restoreFile?.name||tr('Выбрать SQLite backup','Choose SQLite backup')}}</span></label><button class="danger-button" :disabled="busy||pending||!restoreFile||!auth.can('backup.write')" @click="stage"><ArchiveRestore :size="16"/>{{tr('Проверить и подготовить','Validate and stage')}}</button><dl v-if="inspection" class="settings-list"><div><dt>quick_check</dt><dd>{{inspection.quick_check}}</dd></div><div><dt>{{tr('Пользователи','Users')}}</dt><dd>{{inspection.users}}</dd></div><div><dt>{{tr('Устройства','Devices')}}</dt><dd>{{inspection.devices}}</dd></div><div><dt>{{tr('Сессии','Sessions')}}</dt><dd>{{inspection.sessions}}</dd></div></dl></article>
  </section>
</template>

<style scoped>
.backup-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.backup-summary>div{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.backup-summary svg{width:19px;color:var(--accent)}.backup-summary span,.backup-summary strong{display:block}.backup-summary span{color:var(--muted);font-size:9px}.backup-summary strong{margin-bottom:3px;color:var(--text);font-size:18px}.backup-layout{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(290px,.7fr);gap:14px}.padded{padding:18px 18px 0}.restore-card{height:max-content}.restore-card>p{color:var(--muted);font-size:10px;line-height:1.6}.restore-file{display:flex;align-items:center;gap:9px;margin:15px 0;padding:13px;border:1px dashed var(--border);border-radius:9px;color:var(--muted);cursor:pointer}.restore-file input{position:absolute;width:1px;height:1px;opacity:0}.restore-file span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.restore-warning{display:flex;align-items:center;gap:13px;margin-bottom:16px;padding:14px;border:1px solid #f59e0b66;border-radius:12px;background:#f59e0b12;color:#f4bd61}.restore-warning div{flex:1}.restore-warning p{margin:4px 0 0;color:var(--muted);font-size:10px;line-height:1.5}.actions-cell .icon-btn{display:inline-grid}@media(max-width:1000px){.backup-layout{grid-template-columns:1fr}}@media(max-width:700px){.backup-summary{grid-template-columns:repeat(2,1fr)}.restore-warning{align-items:flex-start;flex-wrap:wrap}}
</style>
