<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Ban, Download, Laptop, Pencil, Plus, RotateCcw, ServerCog, Trash2, X } from 'lucide-vue-next'
import { api } from '../api'
import { tr } from '../preferences'
import type { BuilderWorker, ClientBuild, ClientProfile, ClientProfileAssignment } from '../types'

const profiles=ref<ClientProfile[]>([]),assignments=ref<ClientProfileAssignment[]>([]),editing=ref<ClientProfile>(),open=ref(false),saving=ref(false),error=ref('')
const builds=ref<ClientBuild[]>([]),buildBusy=ref(false)
const workers=ref<BuilderWorker[]>([])
const form=reactive({name:'',description:'',platform:'all',enabled:true,id_server:'',relay_server:'',api_server:'',disable_settings:false,force_relay:false,product_name:'Remote Control Server',organization:'',primary_color:'#087BF5',logo_url:'',only_show_local_id:false,prevent_outgoing_connections:false})
const assignment=reactive({profile_id:'',scope_type:'global',scope_id:'',priority:100})
const build=reactive({profile_id:'',target_os:'windows',architecture:'amd64',format:'configuration'})
async function load(){try{[profiles.value,assignments.value,builds.value,workers.value]=await Promise.all([api.clientProfiles(),api.clientProfileAssignments(),api.clientBuilds(),api.builderWorkers()])}catch(reason){error.value=reason instanceof Error?reason.message:tr('Профили клиентов недоступны','Client profiles unavailable')}}
function add(){editing.value=undefined;Object.assign(form,{name:'',description:'',platform:'all',enabled:true,id_server:'',relay_server:'',api_server:'',disable_settings:false,force_relay:false,product_name:'Remote Control Server',organization:'',primary_color:'#087BF5',logo_url:'',only_show_local_id:false,prevent_outgoing_connections:false});open.value=true}
function edit(value:ClientProfile){editing.value=value;Object.assign(form,{name:value.name,description:value.description,platform:value.platform,enabled:value.enabled,id_server:String(value.settings.id_server||''),relay_server:String(value.settings.relay_server||''),api_server:String(value.settings.api_server||''),disable_settings:Boolean(value.settings.disable_settings),force_relay:Boolean(value.settings.force_relay),product_name:String(value.branding.product_name||''),organization:String(value.branding.organization||''),primary_color:String(value.branding.primary_color||'#087BF5'),logo_url:String(value.branding.logo_url||''),only_show_local_id:Boolean(value.branding.only_show_local_id),prevent_outgoing_connections:Boolean(value.branding.prevent_outgoing_connections)});open.value=true}
function payload(){const settings:Record<string,unknown>={disable_settings:form.disable_settings,force_relay:form.force_relay};if(form.id_server)settings.id_server=form.id_server;if(form.relay_server)settings.relay_server=form.relay_server;if(form.api_server)settings.api_server=form.api_server;const branding:Record<string,unknown>={product_name:form.product_name,primary_color:form.primary_color,only_show_local_id:form.only_show_local_id,prevent_outgoing_connections:form.prevent_outgoing_connections};if(form.organization)branding.organization=form.organization;if(form.logo_url)branding.logo_url=form.logo_url;return {name:form.name,description:form.description,platform:form.platform,enabled:form.enabled,settings,branding}}
async function save(){saving.value=true;error.value='';try{editing.value?await api.updateClientProfile(editing.value.id,payload()):await api.createClientProfile(payload());open.value=false;await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось сохранить профиль','Cannot save profile')}finally{saving.value=false}}
async function remove(value:ClientProfile){if(!confirm(`${tr('Удалить профиль','Delete profile')} «${value.name}»?`))return;try{await api.deleteClientProfile(value.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить профиль','Cannot delete profile')}}
async function addAssignment(){try{await api.createClientProfileAssignment({...assignment,scope_id:assignment.scope_type==='global'?'':assignment.scope_id});await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось назначить профиль','Cannot assign profile')}}
async function removeAssignment(value:ClientProfileAssignment){try{await api.deleteClientProfileAssignment(value.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить назначение','Cannot remove assignment')}}
async function download(value:ClientProfile){try{const bundle=await api.clientProfileBundle(value.id);const href=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=href;anchor.download=`rustdesk-${value.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.profile.json`;anchor.click();URL.revokeObjectURL(href)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Bundle недоступен','Bundle unavailable')}}
async function createBuild(){buildBusy.value=true;try{await api.createClientBuild({...build});await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Ошибка сборки','Build failed')}finally{buildBusy.value=false}}
async function downloadBuild(value:ClientBuild){try{const result=await api.clientBuildArtifact(value.id);const href=URL.createObjectURL(result.blob);const anchor=document.createElement('a');anchor.href=href;anchor.download=result.filename;anchor.click();URL.revokeObjectURL(href)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Артефакт недоступен','Artifact unavailable')}}
async function cancelBuild(value:ClientBuild){try{await api.cancelClientBuild(value.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось отменить задание','Could not cancel build')}}
async function retryBuild(value:ClientBuild){try{await api.retryClientBuild(value.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось повторить задание','Could not retry build')}}
function profileName(id:string){return profiles.value.find(value=>value.id===id)?.name||id}
function scopeName(value:string){const names:Record<string,[string,string]>={global:['Глобально','Global'],user:['Пользователь','User'],user_group:['Группа пользователей','User group'],device:['Устройство','Device'],device_group:['Группа устройств','Device group']};return names[value]?tr(...names[value]):value}
onMounted(()=>void load())
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Managed clients</p><h2>{{tr('Профили RustDesk Client','RustDesk Client profiles')}}</h2><p>{{tr('Централизованные серверы, ограничения, брендинг и подписанные пакеты для управляемого развёртывания.','Centralized servers, restrictions, branding, and signed packages for managed deployment.')}}</p></div><button class="primary-button compact" @click="add"><Plus :size="17"/>{{tr('Создать профиль','Create profile')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <section class="card-grid"><article v-for="value in profiles" :key="value.id" class="panel group-card policy-card" :class="{inactive:!value.enabled}"><span class="metric-icon"><Laptop :size="20"/></span><div class="policy-content"><div><span class="badge" :class="value.enabled?'green':'neutral'">{{value.enabled?tr('активен','active'):tr('отключён','disabled')}}</span><span class="badge neutral">{{value.platform}}</span><span class="badge teal">v{{value.version}}</span></div><h3>{{value.name}}</h3><p>{{value.description||tr('Без описания','No description')}}</p></div><div class="policy-actions"><button class="icon-btn" :title="tr('Скачать подписанный пакет','Download signed bundle')" @click="download(value)"><Download :size="15"/></button><button class="icon-btn" :title="tr('Редактировать','Edit')" @click="edit(value)"><Pencil :size="15"/></button><button class="icon-action" :title="tr('Удалить','Delete')" @click="remove(value)"><Trash2 :size="15"/></button></div></article><article v-if="!profiles.length" class="panel empty-state">{{tr('Профилей пока нет.','No profiles yet.')}}</article></section>

  <section class="panel table-panel"><div class="panel-heading"><div><p class="overline">Assignments</p><h3>{{tr('Назначения профилей','Profile assignments')}}</h3></div></div><form class="inline-form" @submit.prevent="addAssignment"><select v-model="assignment.profile_id" required><option value="" disabled>{{tr('Профиль','Profile')}}</option><option v-for="value in profiles" :key="value.id" :value="value.id">{{value.name}}</option></select><select v-model="assignment.scope_type"><option value="global">{{tr('Глобально','Global')}}</option><option value="user">{{tr('Пользователь','User')}}</option><option value="user_group">{{tr('Группа пользователей','User group')}}</option><option value="device">{{tr('Устройство','Device')}}</option><option value="device_group">{{tr('Группа устройств','Device group')}}</option></select><input v-if="assignment.scope_type!=='global'" v-model.trim="assignment.scope_id" placeholder="UUID / RustDesk ID" required/><input v-model.number="assignment.priority" type="number" min="1" max="100000"/><button class="secondary-button">{{tr('Назначить','Assign')}}</button></form><div class="table-wrap"><table><thead><tr><th>{{tr('Профиль','Profile')}}</th><th>{{tr('Область','Scope')}}</th><th>ID</th><th>{{tr('Приоритет','Priority')}}</th><th></th></tr></thead><tbody><tr v-for="value in assignments" :key="value.id"><td>{{profileName(value.profile_id)}}</td><td>{{scopeName(value.scope_type)}}</td><td>{{value.scope_id||tr('Все','All')}}</td><td>{{value.priority}}</td><td><button class="icon-action" :title="tr('Удалить назначение','Remove assignment')" @click="removeAssignment(value)"><Trash2 :size="15"/></button></td></tr><tr v-if="!assignments.length"><td colspan="5" class="empty-cell">{{tr('Назначений пока нет.','No assignments yet.')}}</td></tr></tbody></table></div></section>

  <section class="panel table-panel"><div class="panel-heading"><div><p class="overline">Isolated workers</p><h3>{{tr('Сборочные узлы','Builder workers')}}</h3><p>{{tr('Workers работают на отдельных машинах и получают только задания с ограниченным lease.','Workers run on separate hosts and receive only time-limited leased jobs.')}}</p></div><ServerCog :size="20"/></div><div class="table-wrap"><table><thead><tr><th>{{tr('Узел','Worker')}}</th><th>{{tr('Статус','Status')}}</th><th>{{tr('Возможности','Capabilities')}}</th><th>{{tr('Параллельность','Concurrency')}}</th><th>{{tr('Последний сигнал','Last heartbeat')}}</th></tr></thead><tbody><tr v-for="worker in workers" :key="worker.id"><td><strong>{{worker.name}}</strong><br/><small>{{worker.id}} · {{worker.hostname}} · {{worker.version}}</small></td><td><span class="badge" :class="worker.status==='online'?'green':'neutral'">{{worker.status}}</span></td><td>{{worker.platforms.join(', ')}} · {{worker.architectures.join(', ')}} · {{worker.formats.join(', ')}}</td><td>{{worker.concurrency}}</td><td>{{new Date(worker.last_seen_at).toLocaleString()}}</td></tr><tr v-if="!workers.length"><td colspan="5" class="empty-cell">{{tr('Builder workers ещё не зарегистрированы.','No builder workers registered yet.')}}</td></tr></tbody></table></div></section>

  <section class="panel table-panel">
    <div class="panel-heading"><div><p class="overline">Builder queue</p><h3>{{tr('Сборки клиентов','Client builds')}}</h3><p>{{tr('Конфигурационные пакеты создаются API сразу. Нативные форматы помещаются в очередь отдельного worker.','Configuration packages are created immediately by the API. Native formats are queued for an isolated worker.')}}</p></div></div>
    <form class="inline-form" @submit.prevent="createBuild">
      <select v-model="build.profile_id" required><option value="" disabled>{{tr('Профиль','Profile')}}</option><option v-for="value in profiles" :key="value.id" :value="value.id">{{value.name}}</option></select>
      <select v-model="build.target_os"><option value="windows">Windows</option><option value="linux">Linux</option><option value="macos">macOS</option><option value="android">Android</option></select>
      <select v-model="build.architecture"><option value="amd64">amd64</option><option value="arm64">arm64</option></select>
      <select v-model="build.format"><option value="configuration">Configuration</option><option value="portable">Portable</option><option value="installer">Installer</option><option value="apk">APK</option></select>
      <button class="secondary-button" :disabled="buildBusy">{{buildBusy?tr('Создание…','Creating…'):tr('Создать задание','Create build')}}</button>
    </form>
    <div class="table-wrap"><table><thead><tr><th>{{tr('Артефакт','Artifact')}}</th><th>{{tr('Цель','Target')}}</th><th>{{tr('Статус','Status')}}</th><th>Worker / attempt</th><th>SHA-256</th><th></th></tr></thead><tbody>
      <tr v-for="value in builds" :key="value.id"><td>{{value.artifact_name||value.id}}</td><td>{{value.target_os}}/{{value.architecture}} · {{value.format}}</td><td><span class="badge" :class="value.status==='ready'?'green':'neutral'">{{value.status}}</span><small v-if="value.error"><br/>{{value.error}}</small></td><td>{{value.worker_id||'—'}} / {{value.attempts}}</td><td><code>{{value.sha256?`${value.sha256.slice(0,16)}…`:'—'}}</code></td><td class="table-actions"><button v-if="value.status==='ready'" class="icon-btn" :title="tr('Скачать','Download')" @click="downloadBuild(value)"><Download :size="15"/></button><button v-if="['queued','leased','building','uploading'].includes(value.status)" class="icon-action" :title="tr('Отменить','Cancel')" @click="cancelBuild(value)"><Ban :size="15"/></button><button v-if="['failed','cancelled'].includes(value.status)&&value.attempts<5" class="icon-btn" :title="tr('Повторить','Retry')" @click="retryBuild(value)"><RotateCcw :size="15"/></button></td></tr>
      <tr v-if="!builds.length"><td colspan="6" class="empty-cell">{{tr('Заданий пока нет.','No builds yet.')}}</td></tr>
    </tbody></table></div>
  </section>

  <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal-card" @submit.prevent="save"><div class="modal-heading"><h3>{{editing?tr('Редактирование профиля','Edit profile'):tr('Новый профиль клиента','New client profile')}}</h3><button type="button" class="icon-btn" @click="open=false"><X :size="20"/></button></div><div class="form-grid"><label><span>{{tr('Название','Name')}}</span><input v-model.trim="form.name" minlength="2" maxlength="128" required/></label><label><span>{{tr('Платформа','Platform')}}</span><select v-model="form.platform"><option value="all">{{tr('Все','All')}}</option><option value="windows">Windows</option><option value="linux">Linux</option><option value="macos">macOS</option><option value="android">Android</option></select></label><label><span>{{tr('Описание','Description')}}</span><input v-model.trim="form.description" maxlength="1024"/></label><label><span>ID Server</span><input v-model.trim="form.id_server"/></label><label><span>Relay Server</span><input v-model.trim="form.relay_server"/></label><label><span>API Server</span><input v-model.trim="form.api_server"/></label><label><span>{{tr('Название продукта','Product name')}}</span><input v-model.trim="form.product_name" maxlength="128"/></label><label><span>{{tr('Организация','Organization')}}</span><input v-model.trim="form.organization" maxlength="128"/></label><label><span>{{tr('Основной цвет','Primary color')}}</span><input v-model="form.primary_color" type="color"/></label><label><span>{{tr('HTTPS URL логотипа','Logo HTTPS URL')}}</span><input v-model.trim="form.logo_url" type="url"/></label><label class="check-label"><input v-model="form.enabled" type="checkbox"/><span>{{tr('Профиль включён','Profile enabled')}}</span></label><label class="check-label"><input v-model="form.disable_settings" type="checkbox"/><span>{{tr('Запретить настройки','Disable settings')}}</span></label><label class="check-label"><input v-model="form.force_relay" type="checkbox"/><span>{{tr('Всегда использовать relay','Always use relay')}}</span></label><label class="check-label"><input v-model="form.only_show_local_id" type="checkbox"/><span>{{tr('Показывать только локальный ID','Show local ID only')}}</span></label><label class="check-label"><input v-model="form.prevent_outgoing_connections" type="checkbox"/><span>{{tr('Запретить исходящие подключения','Prevent outgoing connections')}}</span></label></div><div class="modal-actions"><button type="button" class="secondary-button" @click="open=false">{{tr('Отмена','Cancel')}}</button><button class="primary-button compact" :disabled="saving">{{saving?tr('Сохранение…','Saving…'):tr('Сохранить','Save')}}</button></div></form></div>
</template>
