<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { Activity, Ban, CircleStop, ExternalLink, RefreshCw, Search, TimerReset, X } from 'lucide-vue-next'
import { api } from '../api'
import { auth } from '../auth'
import { tr } from '../preferences'
import type { LiveConnection, LiveConnectionSnapshot } from '../types'

const snapshot=ref<LiveConnectionSnapshot>({active:0,stale:0,closed:0,items:[]}),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),search=ref(''),status=ref('active'),selected=ref<LiveConnection>()
let timer:number|undefined
const records=computed(()=>snapshot.value.items.filter(value=>(!status.value||value.status===status.value)&&(!search.value||[value.controller_name,value.controller_login,value.controller_device_id,value.target_rustdesk_id,value.ip].some(field=>field?.toLowerCase().includes(search.value.toLowerCase())))))
async function load(){loading.value=true;error.value='';try{snapshot.value=await api.liveConnections()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить подключения','Unable to load connections')}finally{loading.value=false}}
function duration(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}ч ${m}м`:m?`${m}м ${s}с`:`${s}с`}
function connectionType(value:number){return ({0:'remote control',1:'file transfer',2:'port forwarding',3:'RDP'} as Record<number,string>)[value]||`type ${value}`}
async function contain(){if(!selected.value?.actor_session_id||!confirm(tr('Остановить это подключение? Relay-поток будет разорван, если он управляется сервером; сессия оператора будет отозвана в любом случае.','Stop this connection? A server-managed relay stream will be terminated, and the operator session will always be revoked.')))return;busy.value=true;error.value='';notice.value='';try{const result=await api.containConnection(selected.value.key);notice.value=result.transport_interrupted?tr('Relay-поток физически отключён, авторизационная сессия отозвана.','Relay stream terminated and the authorization session revoked.'):tr('Авторизационная сессия отозвана. Прямое P2P-подключение или уже завершённый relay-поток нельзя подтвердить как физически отключённый.','Authorization session revoked. A direct P2P connection or an already closed relay stream cannot be confirmed as physically interrupted.');selected.value=result.connection;await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось заблокировать подключение','Unable to contain connection')}finally{busy.value=false}}
onMounted(()=>{void load();timer=window.setInterval(load,30_000)})
onBeforeUnmount(()=>{if(timer!==undefined)window.clearInterval(timer)})
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Live operations</p><h2>{{tr('Подключения','Connections')}}</h2><p>{{tr('Кто, с какого устройства и к какому RustDesk ID подключён сейчас или подключался недавно.','See who connected, from which device, and to which RustDesk ID now or recently.')}}</p></div><button class="secondary-button" :disabled="loading" @click="load"><RefreshCw :size="16" :class="{spinning:loading}"/>{{tr('Обновить','Refresh')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <p v-if="notice" class="alert-success">{{notice}}</p>
  <section class="connection-summary"><div class="active"><Activity/><span><strong>{{snapshot.active}}</strong>{{tr('Активных','Active')}}</span></div><div><TimerReset/><span><strong>{{snapshot.stale}}</strong>{{tr('Без сигнала','No heartbeat')}}</span></div><div><CircleStop/><span><strong>{{snapshot.closed}}</strong>{{tr('Завершено','Closed')}}</span></div></section>
  <section class="panel table-panel"><div class="connection-toolbar"><div class="search-box"><Search :size="17"/><input v-model.trim="search" :placeholder="tr('Пользователь, устройство, ID или IP','User, device, ID, or IP')"/></div><select v-model="status"><option value="">{{tr('Все состояния','All states')}}</option><option value="active">{{tr('Активные','Active')}}</option><option value="stale">{{tr('Без сигнала','No heartbeat')}}</option><option value="closed">{{tr('Завершённые','Closed')}}</option></select></div><div class="table-scroll"><table><thead><tr><th>{{tr('Пользователь','User')}}</th><th>{{tr('Исходное устройство','Controller device')}}</th><th>{{tr('Целевой ID','Target ID')}}</th><th>{{tr('Тип','Type')}}</th><th>IP</th><th>{{tr('Начало','Started')}}</th><th>{{tr('Длительность','Duration')}}</th><th>{{tr('Статус','Status')}}</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="empty-cell">{{tr('Загрузка…','Loading…')}}</td></tr><tr v-else-if="!records.length"><td colspan="8" class="empty-cell">{{tr('Подключений не найдено.','No connections found.')}}</td></tr><tr v-for="value in records" :key="value.key" class="connection-row" @click="selected=value"><td><strong>{{value.controller_name||value.controller_login||'—'}}</strong><small v-if="value.controller_login&&value.controller_name!==value.controller_login" class="row-subtle">{{value.controller_login}}</small></td><td>{{value.controller_device_id||'—'}}</td><td><strong>{{value.target_rustdesk_id}}</strong></td><td>{{connectionType(value.connection_type)}}</td><td>{{value.ip||'—'}}</td><td>{{new Date(value.started_at).toLocaleString()}}</td><td>{{duration(value.duration_seconds)}}</td><td><span class="badge" :class="value.status==='active'?'green':value.status==='closed'?'neutral':'danger'">{{value.status==='active'?tr('Активно','Active'):value.status==='closed'?tr('Завершено','Closed'):tr('Нет сигнала','No heartbeat')}}</span></td></tr></tbody></table></div></section>
  <div v-if="selected" class="modal-backdrop" @click.self="selected=undefined"><section class="modal-card connection-detail"><div class="modal-heading"><div><p class="overline">Connection details</p><h3>{{selected.controller_name||selected.controller_login||tr('Подключение','Connection')}} → {{selected.target_rustdesk_id}}</h3></div><button class="icon-btn" @click="selected=undefined"><X :size="19"/></button></div><dl><div><dt>{{tr('Состояние','Status')}}</dt><dd>{{selected.status}}</dd></div><div><dt>{{tr('Пользователь','User')}}</dt><dd>{{selected.controller_name||'—'}}<small>{{selected.controller_login||selected.actor_user_id||'—'}}</small></dd></div><div><dt>{{tr('Серверная сессия','Server session')}}</dt><dd class="mono-cell">{{selected.actor_session_id||'—'}}</dd></div><div><dt>{{tr('Исходное устройство','Controller device')}}</dt><dd>{{selected.controller_device_id||'—'}}</dd></div><div><dt>{{tr('Целевой ID','Target ID')}}</dt><dd>{{selected.target_rustdesk_id}}</dd></div><div><dt>{{tr('Тип подключения','Connection type')}}</dt><dd>{{connectionType(selected.connection_type)}}</dd></div><div><dt>{{tr('Транспорт','Transport')}}</dt><dd>{{selected.transport||'—'}}<small v-if="selected.relay_server">{{selected.relay_server}}</small></dd></div><div><dt>IP</dt><dd>{{selected.ip||'—'}}</dd></div><div><dt>{{tr('Начало / последняя активность','Started / last activity')}}</dt><dd>{{new Date(selected.started_at).toLocaleString()}}<small>{{new Date(selected.last_seen_at).toLocaleString()}}</small></dd></div><div><dt>{{tr('Длительность','Duration')}}</dt><dd>{{duration(selected.duration_seconds)}}</dd></div></dl><p class="connection-warning">{{selected.transport==='relay'?tr('Управляемый relay-поток будет физически разорван с подтверждением HBBR. Сессия оператора также будет отозвана.','The managed relay stream will be physically terminated with HBBR acknowledgement. The operator session will also be revoked.'):tr('Сервер отзовёт авторизационную сессию и запретит повторное подключение. Уже установленный прямой P2P-поток нельзя гарантированно разорвать через сервер.','The server revokes the authorization session and blocks reconnects. An established direct P2P stream cannot be reliably interrupted by the server.')}}</p><div class="modal-actions"><RouterLink class="secondary-button connection-link" :to="`/admin/audit?target_id=${encodeURIComponent(selected.target_rustdesk_id)}`"><ExternalLink :size="15"/>{{tr('Открыть аудит','Open audit')}}</RouterLink><button v-if="selected.status!=='closed'&&selected.actor_session_id&&auth.can('sessions.revoke')" class="danger-button" :disabled="busy" @click="contain"><Ban :size="15"/>{{tr('Остановить подключение','Stop connection')}}</button></div></section></div>
</template>

<style scoped>
.connection-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:16px}.connection-summary>div{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.connection-summary svg{width:19px;color:var(--muted)}.connection-summary .active svg{color:var(--success)}.connection-summary span,.connection-summary strong{display:block}.connection-summary span{color:var(--muted);font-size:10px}.connection-summary strong{margin-bottom:3px;color:var(--text);font-size:20px}.connection-toolbar{display:flex;gap:10px;padding:14px;border-bottom:1px solid var(--border)}.connection-toolbar .search-box{width:min(560px,65%)}.connection-toolbar select{min-width:160px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--text);padding:0 10px}.connection-row{cursor:pointer}.connection-detail{width:min(720px,100%)}.connection-detail dl{display:grid;grid-template-columns:1fr 1fr;gap:1px;margin:0 0 16px;background:var(--border);border:1px solid var(--border);border-radius:11px;overflow:hidden}.connection-detail dl>div{padding:12px;background:var(--surface)}.connection-detail dt{margin-bottom:5px;color:var(--muted);font-size:9px;text-transform:uppercase}.connection-detail dd{margin:0;font-size:11px}.connection-detail dd small{display:block;margin-top:4px;color:var(--muted)}.connection-warning{padding:11px;border:1px solid var(--border);border-radius:9px;color:var(--muted);font-size:10px;line-height:1.5}.connection-link{text-decoration:none}@media(max-width:700px){.connection-summary{grid-template-columns:1fr}.connection-toolbar{flex-direction:column}.connection-toolbar .search-box,.connection-toolbar select{width:100%;height:38px}.connection-detail dl{grid-template-columns:1fr}}
</style>
