<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Boxes, Pencil, Plus, Trash2, UserMinus, UserPlus, Users, X } from 'lucide-vue-next'
import { api } from '../api'
import { t, tr } from '../preferences'
import type { Device, ManagedGroup, ManagedUser } from '../types'

const records=ref<ManagedGroup[]>([]),users=ref<ManagedUser[]>([]),devices=ref<Device[]>([]),members=ref<ManagedUser[]>([])
const open=ref(false),selected=ref<ManagedGroup>(),editing=ref<ManagedGroup>(),loading=ref(true),membersLoading=ref(false),saving=ref(false),error=ref('')
const form=reactive<{name:string;description:string;kind:'user'|'device'}>({name:'',description:'',kind:'device'})
const memberIDs=computed(()=>new Set(members.value.map(user=>user.id)))
const systemGroup=(group:ManagedGroup)=>group.id==='system-pending-users'||group.id==='system-approved-users'
const count=(group:ManagedGroup)=>group.kind==='user'?users.value.filter(user=>user.group_ids?.includes(group.id)).length:devices.value.filter(device=>device.group_id===group.id).length
async function load(){loading.value=true;error.value='';try{[records.value,users.value,devices.value]=await Promise.all([api.groups(),api.users(),api.devices()])}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить группы','Unable to load groups')}finally{loading.value=false}}
function add(){editing.value=undefined;Object.assign(form,{name:'',description:'',kind:'device'});open.value=true}
function edit(group:ManagedGroup){editing.value=group;Object.assign(form,{name:group.name,description:group.description,kind:group.kind});open.value=true}
async function save(){saving.value=true;error.value='';try{if(editing.value)await api.updateGroup(editing.value.id,{name:form.name,description:form.description});else await api.createGroup({...form});open.value=false;await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось сохранить группу','Unable to save group')}finally{saving.value=false}}
async function remove(group:ManagedGroup){if(!confirm(tr(`Удалить группу «${group.name}»? Устройства останутся без группы.`,`Delete group “${group.name}”? Devices will remain ungrouped.`)))return;saving.value=true;error.value='';try{await api.deleteGroup(group.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить группу','Unable to delete group')}finally{saving.value=false}}
async function manage(group:ManagedGroup){if(group.kind!=='user')return;selected.value=group;membersLoading.value=true;try{members.value=await api.groupMembers(group.id)}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить участников','Unable to load members');selected.value=undefined}finally{membersLoading.value=false}}
async function toggleMember(user:ManagedUser){if(!selected.value)return;saving.value=true;error.value='';try{if(memberIDs.value.has(user.id))await api.removeGroupMember(selected.value.id,user.id);else await api.addGroupMember(selected.value.id,user.id);members.value=await api.groupMembers(selected.value.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось изменить членство','Membership update failed')}finally{saving.value=false}}
onMounted(load)
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Policy scopes</p><h2>{{t('managedGroups')}}</h2><p>{{t('groupHelp')}}</p></div><button class="primary-button compact" @click="add"><Plus :size="17"/>{{t('addGroup')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p><p v-if="loading" class="panel empty-state">{{t('loading')}}</p>
  <section v-else class="card-grid"><article v-for="group in records" :key="group.id" class="panel group-card"><span class="metric-icon"><Users v-if="group.kind==='user'" :size="20"/><Boxes v-else :size="20"/></span><div class="policy-content"><span class="badge neutral">{{group.kind==='user'?t('userGroup'):t('deviceGroup')}}</span><span v-if="systemGroup(group)" class="badge neutral">{{tr('Системная','System')}}</span><h3>{{group.name}}</h3><p>{{group.description||'—'}}</p><small>{{count(group)}} {{group.kind==='user'?tr('участников','members'):tr('устройств','devices')}}</small></div><div class="policy-actions"><button v-if="group.kind==='user'" class="secondary-button" @click="manage(group)"><Users :size="14"/>{{tr('Участники','Members')}}</button><button v-if="!systemGroup(group)" class="icon-btn" :title="tr('Редактировать','Edit')" @click="edit(group)"><Pencil :size="15"/></button><button v-if="!systemGroup(group)" class="icon-action" :title="tr('Удалить','Delete')" @click="remove(group)"><Trash2 :size="15"/></button></div></article><article v-if="!records.length" class="panel empty-state">{{t('noRecords')}}</article></section>
  <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal-card" @submit.prevent="save"><div class="modal-heading"><h3>{{editing?tr('Редактировать группу','Edit group'):t('addGroup')}}</h3><button type="button" class="icon-btn" @click="open=false"><X :size="20"/></button></div><label><span>{{t('groupName')}}</span><input v-model="form.name" required minlength="2"/></label><label><span>{{t('description')}}</span><input v-model="form.description"/></label><label><span>{{t('kind')}}</span><select v-model="form.kind" :disabled="!!editing"><option value="user">{{t('userGroup')}}</option><option value="device">{{t('deviceGroup')}}</option></select></label><div class="modal-actions"><button type="button" class="secondary-button" @click="open=false">{{t('cancel')}}</button><button class="primary-button compact" :disabled="saving">{{saving?tr('Сохранение…','Saving…'):editing?tr('Сохранить','Save'):t('create')}}</button></div></form></div>
  <div v-if="selected" class="modal-backdrop" @click.self="selected=undefined"><section class="modal-card membership-modal"><div class="modal-heading"><div><p class="overline">User Group</p><h3>{{selected.name}}</h3></div><button class="icon-btn" @click="selected=undefined"><X :size="20"/></button></div><p class="membership-note">{{tr('Участники применяются в ACL и Strategies до установления соединения.','Members are applied by ACL and Strategies before a connection is established.')}}</p><div v-if="membersLoading" class="empty-state">{{t('loading')}}</div><div v-else class="membership-list"><div v-for="user in users" :key="user.id"><span class="table-avatar">{{(user.display_name||user.username).slice(0,2).toUpperCase()}}</span><div><strong>{{user.display_name||user.username}}</strong><small>{{user.username}} · {{user.role}}</small></div><button class="secondary-button" :class="{member:memberIDs.has(user.id)}" :disabled="saving" @click="toggleMember(user)"><UserMinus v-if="memberIDs.has(user.id)" :size="14"/><UserPlus v-else :size="14"/>{{memberIDs.has(user.id)?tr('Удалить','Remove'):tr('Добавить','Add')}}</button></div></div></section></div>
</template>
