<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { KeyRound, Pencil, Plus, ShieldCheck, Trash2, X } from 'lucide-vue-next'
import { api } from '../api'
import { tr } from '../preferences'
import type { RoleDefinition } from '../types'

const roles=ref<RoleDefinition[]>([]),permissions=ref<string[]>([]),editing=ref<RoleDefinition>(),open=ref(false),busy=ref(false),error=ref('')
const form=reactive({id:'',name:'',description:'',permissions:[] as string[]})
async function load(){error.value='';try{[roles.value,permissions.value]=await Promise.all([api.roles(),api.permissions()])}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить роли','Unable to load roles')}}
function create(){editing.value=undefined;Object.assign(form,{id:'',name:'',description:'',permissions:['admin.portal']});open.value=true}
function edit(role:RoleDefinition){editing.value=role;Object.assign(form,{id:role.id,name:role.name,description:role.description,permissions:[...role.permissions]});open.value=true}
function toggle(permission:string){form.permissions=form.permissions.includes(permission)?form.permissions.filter(value=>value!==permission):[...form.permissions,permission]}
async function save(){busy.value=true;error.value='';try{const payload={id:form.id,name:form.name,description:form.description,permissions:form.permissions};editing.value?await api.updateRole(editing.value.id,payload):await api.createRole(payload);open.value=false;await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось сохранить роль','Unable to save role')}finally{busy.value=false}}
async function remove(role:RoleDefinition){if(!confirm(tr(`Удалить роль «${role.name}»? Её пользователи получат роль «Пользователь».`,`Delete role “${role.name}”? Its users will receive the User role.`)))return;try{await api.deleteRole(role.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить роль','Unable to delete role')}}
onMounted(load)
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Role based access control</p><h2>{{tr('Роли и разрешения','Roles and permissions')}}</h2><p>{{tr('Делегируйте только необходимые разделы и операции административной панели.','Delegate only the administration sections and operations that are required.')}}</p></div><button class="primary-button compact" @click="create"><Plus :size="17"/>{{tr('Создать роль','Create role')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <section class="card-grid"><article v-for="role in roles" :key="role.id" class="panel policy-card"><span class="metric-icon"><ShieldCheck :size="20"/></span><div class="policy-content"><div><span class="badge" :class="role.system?'neutral':'teal'">{{role.system?tr('Системная','System'):tr('Пользовательская','Custom')}}</span></div><h3>{{role.name}}</h3><p>{{role.description||tr('Без описания','No description')}}</p><div class="user-group-badges"><span v-for="permission in role.permissions" :key="permission" class="badge neutral">{{permission==='*'?tr('Все разрешения','All permissions'):permission}}</span><span v-if="!role.permissions.length" class="muted-text">{{tr('Только личный кабинет и RustDesk Client','User portal and RustDesk Client only')}}</span></div></div><div v-if="!role.system" class="policy-actions"><button class="icon-btn" :title="tr('Редактировать','Edit')" @click="edit(role)"><Pencil :size="16"/></button><button class="icon-action" :title="tr('Удалить','Delete')" @click="remove(role)"><Trash2 :size="16"/></button></div></article></section>
  <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal-card user-editor-modal" @submit.prevent="save"><div class="modal-heading"><div><p class="overline">RBAC</p><h3>{{editing?tr('Редактирование роли','Edit role'):tr('Новая роль','New role')}}</h3></div><button type="button" class="icon-btn" @click="open=false"><X :size="20"/></button></div><div class="form-grid"><label><span>{{tr('Идентификатор','Identifier')}}</span><input v-model="form.id" :disabled="!!editing" required pattern="[a-z][a-z0-9_-]{1,63}" placeholder="helpdesk"/></label><label><span>{{tr('Название','Name')}}</span><input v-model="form.name" required minlength="2" maxlength="128"/></label></div><label><span>{{tr('Описание','Description')}}</span><input v-model="form.description" maxlength="512"/></label><fieldset class="user-groups-field"><legend><KeyRound :size="15"/> {{tr('Разрешения','Permissions')}}</legend><div><label v-for="permission in permissions" :key="permission" :class="{selected:form.permissions.includes(permission)}"><input type="checkbox" :checked="form.permissions.includes(permission)" @change="toggle(permission)"/><span>{{permission}}</span></label></div></fieldset><div class="modal-actions"><button type="button" class="secondary-button" @click="open=false">{{tr('Отмена','Cancel')}}</button><button class="primary-button compact" :disabled="busy">{{busy?tr('Сохранение…','Saving…'):tr('Сохранить','Save')}}</button></div></form></div>
</template>
