<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Ban, CheckCircle2, ChevronLeft, ChevronRight, Clock3, RefreshCw, Search, Shield, XCircle } from 'lucide-vue-next'
import { api } from '../api'
import { auth } from '../auth'
import { t, tr } from '../preferences'
import type { SessionRecord, SessionSummary } from '../types'

const records=ref<SessionRecord[]>([]),summary=ref<SessionSummary>(),loading=ref(true),busy=ref(false),error=ref(''),search=ref(''),status=ref('active'),checked=ref<string[]>([])
const limit=50,offset=ref(0),total=ref(0)
const pageNumber=computed(()=>Math.floor(offset.value/limit)+1),pageCount=computed(()=>Math.max(1,Math.ceil(total.value/limit)))
const revocable=computed(()=>records.value.filter(value=>value.status==='active'&&!value.current))
const allChecked=computed(()=>revocable.value.length>0&&revocable.value.every(value=>checked.value.includes(value.id)))
async function load(reset=false){if(reset)offset.value=0;loading.value=true;error.value='';try{const [page,stats]=await Promise.all([api.querySessions({limit,offset:offset.value,status:status.value||undefined,search:search.value||undefined}),api.sessionSummary()]);records.value=page.sessions;total.value=page.total;summary.value=stats;checked.value=checked.value.filter(id=>page.sessions.some(value=>value.id===id&&value.status==='active'&&!value.current))}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить сессии','Unable to load sessions')}finally{loading.value=false}}
function toggleAll(){const ids=revocable.value.map(value=>value.id);checked.value=allChecked.value?checked.value.filter(id=>!ids.includes(id)):[...new Set([...checked.value,...ids])]}
async function revoke(session:SessionRecord){if(!confirm(tr(`Отозвать сессию ${session.username} на ${session.client_device_id||session.ip}?`,`Revoke ${session.username}'s session on ${session.client_device_id||session.ip}?`)))return;busy.value=true;try{await api.revokeSession(session.id);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось отозвать сессию','Unable to revoke session')}finally{busy.value=false}}
async function revokeSelected(){if(!checked.value.length||!confirm(tr(`Отозвать выбранные сессии: ${checked.value.length}?`,`Revoke ${checked.value.length} selected sessions?`)))return;busy.value=true;try{await api.bulkRevokeSessions(checked.value);checked.value=[];await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось отозвать сессии','Unable to revoke sessions')}finally{busy.value=false}}
function changePage(direction:number){offset.value=Math.max(0,Math.min((pageCount.value-1)*limit,offset.value+direction*limit));void load()}
function shortAgent(value:string){if(!value)return '—';return value.length>52?`${value.slice(0,52)}…`:value}
onMounted(()=>load())
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Session Security Center</p><h2>{{t('activeSessions')}}</h2><p>{{tr('Управление всеми активными, отозванными и истёкшими входами пользователей.','Manage every active, revoked, and expired user sign-in.')}}</p></div><button class="secondary-button" :disabled="loading" @click="load()"><RefreshCw :size="16" :class="{spinning:loading}"/>{{t('refresh')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <section class="session-summary"><div><Shield :size="18"/><span><strong>{{summary?.total??0}}</strong>{{tr('Всего','Total')}}</span></div><div class="active"><CheckCircle2 :size="18"/><span><strong>{{summary?.active??0}}</strong>{{tr('Активных','Active')}}</span></div><div class="revoked"><Ban :size="18"/><span><strong>{{summary?.revoked??0}}</strong>{{tr('Отозвано','Revoked')}}</span></div><div><Clock3 :size="18"/><span><strong>{{summary?.expired??0}}</strong>{{tr('Истекло','Expired')}}</span></div></section>
  <section class="panel table-panel">
    <div v-if="checked.length" class="bulk-bar"><strong>{{tr('Выбрано','Selected')}}: {{checked.length}}</strong><span>{{tr('Новые подключения по этим сессиям будут немедленно заблокированы HBBS.','HBBS will immediately block new connections from these sessions.')}}</span><button class="secondary-button" @click="checked=[]">{{tr('Снять выбор','Clear')}}</button><button class="danger-button" :disabled="busy||!auth.can('sessions.revoke')" @click="revokeSelected"><XCircle :size="15"/>{{tr('Отозвать','Revoke')}}</button></div>
    <form class="session-toolbar" @submit.prevent="load(true)"><div class="search-box"><Search :size="17"/><input v-model.trim="search" :placeholder="tr('Пользователь, устройство, IP или клиент','User, device, IP, or client')"/></div><select v-model="status"><option value="">{{tr('Все состояния','All states')}}</option><option value="active">{{tr('Активные','Active')}}</option><option value="revoked">{{tr('Отозванные','Revoked')}}</option><option value="expired">{{tr('Истёкшие','Expired')}}</option></select><button class="primary-button compact">{{tr('Применить','Apply')}}</button></form>
    <div class="table-scroll"><table><thead><tr><th class="select-cell"><input type="checkbox" :checked="allChecked" :disabled="!revocable.length" @change="toggleAll"/></th><th>{{tr('Пользователь','User')}}</th><th>{{t('deviceId')}}</th><th>{{t('ipAddress')}}</th><th>{{tr('Клиент','Client')}}</th><th>{{t('lastSeen')}}</th><th>{{t('expires')}}</th><th>{{tr('Статус','Status')}}</th><th></th></tr></thead><tbody>
      <tr v-if="loading"><td colspan="9" class="empty-cell">{{t('loading')}}</td></tr><tr v-else-if="!records.length"><td colspan="9" class="empty-cell">{{t('noRecords')}}</td></tr>
      <tr v-for="session in records" :key="session.id" :class="{selected:checked.includes(session.id)}"><td class="select-cell"><input v-if="session.status==='active'&&!session.current" v-model="checked" type="checkbox" :value="session.id"/></td><td><strong>{{session.display_name||session.username}}</strong><small class="row-subtle">{{session.username}} · {{session.user_id.slice(0,8)}}</small></td><td>{{session.client_device_id||'—'}}<small v-if="session.current" class="current-label">{{tr('Текущая сессия','Current session')}}</small></td><td>{{session.ip||'—'}}</td><td :title="session.user_agent">{{shortAgent(session.user_agent)}}</td><td>{{new Date(session.last_seen_at).toLocaleString()}}</td><td>{{new Date(session.expires_at).toLocaleString()}}</td><td><span class="badge" :class="session.status==='active'?'green':session.status==='revoked'?'danger':'neutral'">{{session.status==='active'?tr('Активна','Active'):session.status==='revoked'?tr('Отозвана','Revoked'):tr('Истекла','Expired')}}</span></td><td class="actions-cell"><button v-if="session.status==='active'&&!session.current&&auth.can('sessions.revoke')" class="text-button danger-text" :disabled="busy" @click="revoke(session)">{{t('revoke')}}</button></td></tr>
    </tbody></table></div>
    <footer class="session-pagination"><span>{{total?offset+1:0}}–{{Math.min(offset+limit,total)}} {{tr('из','of')}} {{total}}</span><div><button class="icon-btn" :disabled="offset===0" @click="changePage(-1)"><ChevronLeft :size="17"/></button><strong>{{pageNumber}} / {{pageCount}}</strong><button class="icon-btn" :disabled="pageNumber>=pageCount" @click="changePage(1)"><ChevronRight :size="17"/></button></div></footer>
  </section>
</template>

<style scoped>
.session-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.session-summary>div{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.session-summary svg{color:var(--muted)}.session-summary .active svg{color:var(--success)}.session-summary .revoked svg{color:var(--danger)}.session-summary span,.session-summary strong{display:block}.session-summary span{color:var(--muted);font-size:10px}.session-summary strong{margin-bottom:3px;color:var(--text);font-size:20px}.session-toolbar{display:flex;align-items:center;gap:9px;padding:14px;border-bottom:1px solid var(--border)}.session-toolbar .search-box{width:min(520px,60%)}.session-toolbar select{height:36px;padding:0 10px;border:1px solid var(--border);border-radius:8px;background:var(--surface-2);color:var(--text);font-size:10px}.current-label{display:block;margin-top:4px;color:var(--accent);font-size:8px}.session-pagination{display:flex;align-items:center;justify-content:space-between;padding:11px 16px;border-top:1px solid var(--border);color:var(--muted);font-size:10px}.session-pagination>div{display:flex;align-items:center;gap:10px}@media(max-width:760px){.session-summary{grid-template-columns:repeat(2,1fr)}.session-toolbar{align-items:stretch;flex-direction:column}.session-toolbar .search-box,.session-toolbar select,.session-toolbar button{width:100%}}
</style>
