<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Check, Image, Pencil, Plus, RefreshCw, Search, ShieldCheck, Trash2, Unlink, Upload, UserRoundX, X } from 'lucide-vue-next'
import { api } from '../api'
import { auth } from '../auth'
import { tr } from '../preferences'
import type { ManagedGroup, ManagedUser, OIDCIdentity, RoleDefinition } from '../types'

const users=ref<ManagedUser[]>([]),groups=ref<ManagedGroup[]>([]),identities=ref<OIDCIdentity[]>([]),roles=ref<RoleDefinition[]>([])
const loading=ref(true),saving=ref(false),error=ref(''),notice=ref(''),search=ref('')
const createOpen=ref(false),editing=ref<ManagedUser>()
const avatarFile=ref<File|null>(null),avatarBusy=ref(false),avatarVersion=ref(Date.now())
const form=reactive({username:'',display_name:'',email:'',phone:'',password:'',confirmation:'',role:'user',enabled:true,group_ids:[] as string[]})
const userGroups=computed(()=>groups.value.filter(value=>value.kind==='user'&&!value.id.startsWith('system-')))
const filtered=computed(()=>{const needle=search.value.trim().toLowerCase();return needle?users.value.filter(user=>`${user.username} ${user.display_name} ${user.email} ${user.phone}`.toLowerCase().includes(needle)):users.value})
const canWrite=computed(()=>auth.can('users.write'))

async function load(){loading.value=true;error.value='';try{users.value=await api.users();const [groupResult,identityResult,roleResult]=await Promise.allSettled([api.groups(),api.adminOIDCIdentities(),api.roles()]);groups.value=groupResult.status==='fulfilled'?groupResult.value:[];identities.value=identityResult.status==='fulfilled'?identityResult.value:[];roles.value=roleResult.status==='fulfilled'?roleResult.value:[]}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить пользователей','Unable to load users')}finally{loading.value=false}}
function resetForm(){Object.assign(form,{username:'',display_name:'',email:'',phone:'',password:'',confirmation:'',role:'user',enabled:true,group_ids:[]})}
function openCreate(){editing.value=undefined;resetForm();createOpen.value=true;error.value='';notice.value=''}
function openEdit(user:ManagedUser){createOpen.value=false;editing.value=user;Object.assign(form,{username:user.username,display_name:user.display_name,email:user.email,phone:user.phone||'',password:'',confirmation:'',role:user.role,enabled:user.enabled,group_ids:(user.group_ids||[]).filter(id=>!id.startsWith('system-'))});error.value='';notice.value=''}
function closeEditor(){createOpen.value=false;editing.value=undefined;avatarFile.value=null;resetForm()}
function toggleGroup(id:string){form.group_ids=form.group_ids.includes(id)?form.group_ids.filter(value=>value!==id):[...form.group_ids,id]}

async function save(){if(form.password!==form.confirmation){error.value=tr('Пароли не совпадают.','Passwords do not match.');return}saving.value=true;error.value='';notice.value='';try{const payload={username:form.username.trim().toLowerCase(),display_name:form.display_name.trim(),email:form.email.trim(),phone:form.phone.trim(),password:form.password,role:form.role,enabled:form.enabled,group_ids:form.group_ids};if(editing.value){const name=editing.value.username;await api.updateUser(editing.value.id,payload);notice.value=tr(`Карточка пользователя ${name} обновлена. Активные сессии отозваны.`,`User ${name} updated. Active sessions were revoked.`)}else{await api.createUser(payload);notice.value=tr('Пользователь создан.','User created.')}closeEditor();await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось сохранить пользователя','Unable to save user')}finally{saving.value=false}}
async function remove(user:ManagedUser){if(!window.confirm(tr(`Удалить пользователя ${user.username}? Будут удалены его сессии, персональные адресные книги и привязки. Отменить это действие нельзя.`,`Delete user ${user.username}? Sessions, personal address books, and linked identities will be deleted. This cannot be undone.`)))return;saving.value=true;error.value='';notice.value='';try{await api.deleteUser(user.id);notice.value=tr(`Пользователь ${user.username} удалён.`,`User ${user.username} deleted.`);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить пользователя','Unable to delete user')}finally{saving.value=false}}
async function toggle(user:ManagedUser){error.value='';try{await api.setEnabled(user.id,!user.enabled);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось изменить статус','Unable to change status')}}
async function setApproval(user:ManagedUser,status:'approved'|'rejected'){error.value='';try{status==='approved'?await api.approveUser(user.id):await api.rejectUser(user.id);notice.value=status==='approved'?tr(`Пользователь ${user.username} одобрен.`,`User ${user.username} approved.`):tr(`Заявка ${user.username} отклонена.`,`Registration ${user.username} rejected.`);await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось изменить статус регистрации','Unable to change registration status')}}
function userIdentities(id:string){return identities.value.filter(value=>value.user_id===id)}
async function unlinkIdentity(value:OIDCIdentity){if(!window.confirm(tr(`Отозвать OIDC-привязку ${value.email||value.subject}?`,`Unlink OIDC identity ${value.email||value.subject}?`)))return;try{await api.adminUnlinkOIDC(value);identities.value=await api.adminOIDCIdentities()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось отозвать OIDC-привязку','Unable to unlink OIDC identity')}}
function selectAvatar(event:Event){avatarFile.value=(event.target as HTMLInputElement).files?.[0]||null}
async function uploadAvatar(){if(!editing.value||!avatarFile.value)return;avatarBusy.value=true;try{await api.uploadUserAvatar(editing.value.id,avatarFile.value);avatarFile.value=null;avatarVersion.value=Date.now();notice.value=tr('Аватар пользователя обновлён. Для RustDesk Client потребуется повторный вход.','User avatar updated. RustDesk Client must sign in again.')}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось загрузить аватар','Could not upload avatar')}finally{avatarBusy.value=false}}
async function resetAvatar(){if(!editing.value)return;avatarBusy.value=true;try{await api.resetUserAvatar(editing.value.id);avatarVersion.value=Date.now();notice.value=tr('Персональный аватар удалён, будет использован глобальный.','Personal avatar removed; the global avatar will be used.')}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить аватар','Could not remove avatar')}finally{avatarBusy.value=false}}
onMounted(load)
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Identity directory</p><h2>{{tr('Пользователи','Users')}}</h2><p>{{tr('Полное управление учётными записями, группами и доступом.','Full management of accounts, groups, and access.')}}</p></div><button v-if="canWrite" class="primary-button compact" @click="openCreate"><Plus :size="17"/>{{tr('Добавить пользователя','Add user')}}</button></section>
  <div v-if="error" class="alert-error" role="alert">{{error}}</div><div v-if="notice" class="alert-success" role="status">{{notice}}</div>
  <section class="panel table-panel"><div class="table-toolbar"><div class="search-box"><Search :size="17"/><input v-model="search" :placeholder="tr('Логин, имя, email или телефон','Login, name, email, or phone')"/></div><button class="secondary-button" :disabled="loading" @click="load"><RefreshCw :size="16" :class="{spinning:loading}"/>{{tr('Обновить','Refresh')}}</button></div>
    <div class="table-scroll"><table><thead><tr><th>{{tr('Пользователь','User')}}</th><th>{{tr('Группы','Groups')}}</th><th>{{tr('Роль','Role')}}</th><th>{{tr('Статус','Status')}}</th><th>OIDC</th><th></th></tr></thead><tbody>
      <tr v-if="loading"><td colspan="6" class="empty-cell">{{tr('Загрузка…','Loading…')}}</td></tr><tr v-else-if="!filtered.length"><td colspan="6" class="empty-cell">{{tr('Пользователи не найдены.','No users found.')}}</td></tr>
      <tr v-for="user in filtered" :key="user.id"><td><div class="user-cell"><span class="table-avatar">{{(user.display_name||user.username).slice(0,2).toUpperCase()}}</span><div><strong>{{user.display_name||user.username}}</strong><small>@{{user.username}}<template v-if="user.email"> · {{user.email}}</template><template v-if="user.phone"> · {{user.phone}}</template></small></div></div></td>
        <td><div class="user-group-badges"><span v-for="id in (user.group_ids||[]).filter(id=>!id.startsWith('system-'))" :key="id" class="badge neutral">{{groups.find(value=>value.id===id)?.name||id}}</span><span v-if="!(user.group_ids||[]).some(id=>!id.startsWith('system-'))" class="muted-text">—</span></div></td>
        <td><span class="role-badge"><ShieldCheck v-if="user.is_admin" :size="14"/>{{user.role}}</span></td><td><span class="status-text" :class="{disabled:!user.enabled||user.approval_status!=='approved'}"><span></span>{{!user.enabled?tr('Отключён','Disabled'):user.approval_status==='pending'?tr('Ожидает одобрения','Pending approval'):user.approval_status==='rejected'?tr('Отклонён','Rejected'):tr('Активен','Active')}}</span></td>
        <td><div v-if="userIdentities(user.id).length" class="inline-identities"><span v-for="item in userIdentities(user.id)" :key="`${item.provider}:${item.subject}`" class="badge neutral">{{item.provider}}<button :title="tr('Отозвать','Unlink')" @click="unlinkIdentity(item)"><Unlink :size="12"/></button></span></div><span v-else class="muted-text">—</span></td>
        <td class="actions-cell"><template v-if="canWrite"><button v-if="user.approval_status!=='approved'" class="text-button approval-action" @click="setApproval(user,'approved')"><Check :size="14"/>{{tr('Одобрить','Approve')}}</button><button v-if="user.approval_status==='pending'" class="text-button danger-text" @click="setApproval(user,'rejected')">{{tr('Отклонить','Reject')}}</button><button class="icon-btn" :title="tr('Редактировать','Edit')" @click="openEdit(user)"><Pencil :size="16"/></button><button class="icon-btn" :title="user.enabled?tr('Отключить','Disable'):tr('Активировать','Enable')" @click="toggle(user)"><UserRoundX :size="16"/></button><button class="icon-action" :title="tr('Удалить','Delete')" @click="remove(user)"><Trash2 :size="16"/></button></template></td></tr>
    </tbody></table></div>
  </section>
  <div v-if="createOpen||editing" class="modal-backdrop" @click.self="closeEditor"><form class="modal-card user-editor-modal" @submit.prevent="save"><div class="modal-heading"><div><p class="overline">{{tr('Управление учётной записью','Account management')}}</p><h3>{{editing?tr('Карточка пользователя','User details'):tr('Новый пользователь','New user')}}</h3></div><button type="button" class="icon-btn" @click="closeEditor"><X :size="20"/></button></div>
    <div class="form-grid"><label><span>{{tr('Логин','Login')}}</span><input v-model="form.username" required minlength="2" maxlength="64" autocomplete="off"/></label><label><span>{{tr('Псевдоним / отображаемое имя','Alias / display name')}}</span><input v-model="form.display_name" maxlength="256"/></label><label><span>Email</span><input v-model="form.email" type="email" maxlength="320"/></label><label><span>{{tr('Телефон','Phone')}}</span><input v-model="form.phone" type="tel" maxlength="64" placeholder="+7 999 000-00-00"/></label><label><span>{{editing?tr('Новый пароль (оставьте пустым, чтобы не менять)','New password (leave blank to keep current)'):tr('Пароль','Password')}}</span><input v-model="form.password" type="password" :required="!editing" maxlength="1024" autocomplete="new-password"/></label><label><span>{{tr('Повторите пароль','Confirm password')}}</span><input v-model="form.confirmation" type="password" :required="!!form.password" maxlength="1024" autocomplete="new-password"/></label><label><span>{{tr('Роль','Role')}}</span><select v-model="form.role"><option v-for="role in roles" :key="role.id" :value="role.id">{{role.name}}</option></select></label><label class="check-label"><input v-model="form.enabled" type="checkbox"/><span>{{tr('Учётная запись активна','Account enabled')}}</span></label></div>
    <section v-if="editing" class="user-avatar-editor"><img :src="`${editing.avatar}?v=${avatarVersion}`" alt=""/><div><strong>{{tr('Аватар пользователя','User avatar')}}</strong><small>{{tr('Персональный аватар имеет приоритет над глобальным. PNG или JPEG до 2 МБ.','A personal avatar overrides the global avatar. PNG or JPEG up to 2 MiB.')}}</small><label class="logo-file"><Image :size="16"/><input type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg" :disabled="avatarBusy" @change="selectAvatar"/><span>{{avatarFile?.name||tr('Выбрать файл','Choose file')}}</span></label><div class="logo-actions"><button type="button" class="secondary-button" :disabled="avatarBusy||!avatarFile" @click="uploadAvatar"><Upload :size="15"/>{{tr('Загрузить','Upload')}}</button><button type="button" class="secondary-button" :disabled="avatarBusy" @click="resetAvatar"><Trash2 :size="15"/>{{tr('Использовать глобальный','Use global')}}</button></div></div></section>
    <fieldset class="user-groups-field"><legend>{{tr('Группы пользователя','User groups')}}</legend><div><label v-for="group in userGroups" :key="group.id" :class="{selected:form.group_ids.includes(group.id)}"><input type="checkbox" :checked="form.group_ids.includes(group.id)" @change="toggleGroup(group.id)"/><span>{{group.name}}</span></label><p v-if="!userGroups.length" class="muted-text">{{tr('Пользовательских групп пока нет.','No user groups yet.')}}</p></div></fieldset>
    <p v-if="editing" class="password-warning"><ShieldCheck :size="17"/>{{tr('После сохранения действующие сессии пользователя будут отозваны.','Saving will revoke all active sessions for this user.')}}</p><div class="modal-actions"><button type="button" class="secondary-button" @click="closeEditor">{{tr('Отмена','Cancel')}}</button><button class="primary-button compact" :disabled="saving">{{saving?tr('Сохранение…','Saving…'):editing?tr('Сохранить изменения','Save changes'):tr('Создать пользователя','Create user')}}</button></div></form></div>
</template>
