<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ClipboardCopy, Pencil, Plus, Send, Trash2, X } from 'lucide-vue-next'
import { api } from '../api'
import { tr } from '../preferences'
import type { Webhook, WebhookDelivery } from '../types'

const records=ref<Webhook[]>([]), eventTypes=ref<string[]>([]), deliveries=ref<WebhookDelivery[]>([]), selected=ref<Webhook>(), editing=ref<Webhook>(), open=ref(false), saving=ref(false), error=ref(''), secret=ref('')
const form=reactive({name:'',url:'',events:['*'] as string[],enabled:true})
async function load(){try{const result=await api.webhooks();records.value=result.webhooks;eventTypes.value=result.event_types}catch(reason){error.value=reason instanceof Error?reason.message:tr('Webhooks недоступны','Webhooks unavailable')}}
function add(){editing.value=undefined;Object.assign(form,{name:'',url:'',events:['*'],enabled:true});secret.value='';open.value=true}
function edit(value:Webhook){editing.value=value;Object.assign(form,{name:value.name,url:value.url,events:[...value.events],enabled:value.enabled});secret.value='';open.value=true}
function toggleEvent(value:string){form.events=form.events.includes(value)?form.events.filter(item=>item!==value):[...form.events,value];if(value==='*'&&form.events.includes('*'))form.events=['*'];else if(value!=='*')form.events=form.events.filter(item=>item!=='*')}
async function save(){saving.value=true;error.value='';try{if(editing.value){await api.updateWebhook(editing.value.id,{...form})}else{const result=await api.createWebhook({...form});secret.value=result.secret}if(editing.value)open.value=false;await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Cannot save webhook'}finally{saving.value=false}}
async function remove(value:Webhook){if(!confirm(`${tr('Удалить webhook','Delete webhook')} «${value.name}»?`))return;try{await api.deleteWebhook(value.id);if(selected.value?.id===value.id){selected.value=undefined;deliveries.value=[]}await load()}catch(reason){error.value=reason instanceof Error?reason.message:tr('Не удалось удалить webhook','Cannot delete webhook')}}
async function showDeliveries(value:Webhook){selected.value=value;try{deliveries.value=await api.webhookDeliveries(value.id)}catch(reason){error.value=reason instanceof Error?reason.message:'Delivery log unavailable'}}
async function copySecret(){try{await navigator.clipboard.writeText(secret.value)}catch{error.value=tr('Не удалось скопировать секрет','Could not copy secret')}}
onMounted(()=>void load())
</script>

<template>
  <section class="section-heading"><div><p class="eyebrow">Integrations</p><h2>{{tr('Webhooks и уведомления','Webhooks and notifications')}}</h2><p>{{tr('Подписки на серверные события с HMAC-SHA256, повторными попытками и журналом доставок.','Server event subscriptions with HMAC-SHA256, retries, and delivery history.')}}</p></div><button class="primary-button compact" @click="add"><Plus :size="17"/>{{tr('Добавить webhook','Add webhook')}}</button></section>
  <p v-if="error" class="alert-error">{{error}}</p>
  <section class="card-grid"><article v-for="value in records" :key="value.id" class="panel group-card policy-card" :class="{inactive:!value.enabled}" @click="showDeliveries(value)"><span class="metric-icon"><Send :size="20"/></span><div class="policy-content"><div><span class="badge" :class="value.enabled?'green':'neutral'">{{value.enabled?'active':'disabled'}}</span><span class="badge neutral">{{value.events.includes('*')?'all events':`${value.events.length} events`}}</span></div><h3>{{value.name}}</h3><p>{{value.url}}</p></div><div class="policy-actions"><button class="icon-btn" @click.stop="edit(value)"><Pencil :size="15"/></button><button class="icon-action" @click.stop="remove(value)"><Trash2 :size="15"/></button></div></article></section>
  <section v-if="selected" class="panel table-panel"><div class="panel-heading"><div><p class="overline">Delivery log</p><h3>{{selected.name}}</h3></div></div><div class="table-wrap"><table><thead><tr><th>{{tr('Событие','Event')}}</th><th>{{tr('Статус','Status')}}</th><th>{{tr('Попытки','Attempts')}}</th><th>HTTP</th><th>{{tr('Время','Time')}}</th><th>{{tr('Ошибка','Error')}}</th></tr></thead><tbody><tr v-for="item in deliveries" :key="item.id"><td>{{item.event_type}}</td><td><span class="badge" :class="item.status==='delivered'?'green':'neutral'">{{item.status}}</span></td><td>{{item.attempts}}</td><td>{{item.response_code||'—'}}</td><td>{{new Date(item.created_at).toLocaleString()}}</td><td>{{item.last_error||'—'}}</td></tr></tbody></table></div></section>
  <div v-if="open" class="modal-backdrop" @click.self="!secret&&(open=false)"><form class="modal-card" @submit.prevent="save"><div class="modal-heading"><h3>{{editing?tr('Редактирование webhook','Edit webhook'):tr('Новый webhook','New webhook')}}</h3><button v-if="!secret" type="button" class="icon-btn" @click="open=false"><X :size="20"/></button></div><template v-if="secret"><p>{{tr('Секрет показывается только один раз. Получатель использует его для проверки заголовка','The secret is shown only once. The receiver uses it to verify the header')}} <code>X-RDS-Signature</code>.</p><div class="recovery-codes"><code>{{secret}}</code><button type="button" class="secondary-button" @click="copySecret"><ClipboardCopy :size="16"/>{{tr('Скопировать','Copy')}}</button></div><div class="modal-actions"><button type="button" class="primary-button compact" @click="open=false">{{tr('Готово','Done')}}</button></div></template><template v-else><div class="form-grid"><label><span>{{tr('Название','Name')}}</span><input v-model.trim="form.name" minlength="2" maxlength="128" required/></label><label><span>HTTPS URL</span><input v-model.trim="form.url" type="url" maxlength="2048" placeholder="https://hooks.example.com/rustdesk" required/></label><label class="check-label"><input v-model="form.enabled" type="checkbox"/><span>{{tr('Включён','Enabled')}}</span></label></div><div class="strategy-options"><label v-for="eventType in eventTypes" :key="eventType" class="check-label"><input type="checkbox" :checked="form.events.includes(eventType)" @change="toggleEvent(eventType)"/><span>{{eventType==='*'?tr('Все события','All events'):eventType}}</span></label></div><div class="modal-actions"><button type="button" class="secondary-button" @click="open=false">{{tr('Отмена','Cancel')}}</button><button class="primary-button compact" :disabled="saving||!form.events.length">{{saving?tr('Сохранение…','Saving…'):tr('Сохранить','Save')}}</button></div></template></form></div>
</template>
